eliastre100_poke_battle_register:
    path:     /register/{name}/{password}/{email}
    defaults: { _controller: Eliastre100PokeBattleBundle:Login:register }

eliastre100_poke_battle_login:
    path:     /login/{name}/{password}
    defaults: { _controller: Eliastre100PokeBattleBundle:Login:login }

eliastre100_poke_battle_browse:
    path:     /{token}/browse
    defaults: { _controller: Eliastre100PokeBattleBundle:Lobby:browse }

eliastre100_poke_battle_host:
    path:     /{token}/host/{name}
    defaults: { _controller: Eliastre100PokeBattleBundle:Lobby:host }

