<?php

namespace Eliastre100\PokeBattleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends EntityRepository
{
}
